apiVersion: v1
kind: Namespace
metadata:
  name: ghost-blog
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ghost-blog-deployment
  namespace: ghost-blog
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1 
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3.42
        env:
        - name: NODE_ENV
          value: development   
        ports:
        - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-blog-service
  namespace: ghost-blog
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #traefik.ingress.kubernetes.io/router.tls: "true" 
  name: ghostblog-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ghost-blog-service
            port:
              number: 80
        path: /ghost
        pathType: Prefix
